version: "3.2"
services:
  db:
    image: mongo 
    volumes:
      - type: volume
        source: ~/data/db
        target: /data/db
    ports:
      - "27017:27017"
      - "28017:28017"
    expose:
      - "27017"
    networks:
      - webnet
  api:
    image: "node:8"
    working_dir: /home/node/app
    volumes: 
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - webnet
networks:
  webnet:
